<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="obj\Debug\net10.0\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs" />
    <Compile Include="obj\Debug\net10.0\RestaurantAPI.DataAccess.AssemblyInfo.cs" />
    <Compile Include="obj\Debug\net10.0\RestaurantAPI.DataAccess.GlobalUsings.g.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net10.0\RestaurantAPI.DataAccess.deps.json" />
    <Content Include="bin\Debug\net10.0\RestaurantAPI.DataAccess.runtimeconfig.json" />
    <Content Include="obj\Debug\net10.0\RestaurantAPI.DataAccess.csproj.FileListAbsolute.txt" />
    <Content Include="obj\project.assets.json" />
    <Content Include="obj\RestaurantAPI.DataAccess.csproj.nuget.dgspec.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RestaurantAPI.Domain\RestaurantAPI.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\net10.0\RestaurantAPI.DataAccess.dll" />
    <None Include="bin\Debug\net10.0\RestaurantAPI.DataAccess.pdb" />
    <None Include="bin\Debug\net10.0\RestaurantAPI.Domain.dll" />
    <None Include="bin\Debug\net10.0\RestaurantAPI.Domain.pdb" />
    <None Include="obj\Debug\net10.0\refint\RestaurantAPI.DataAccess.dll" />
    <None Include="obj\Debug\net10.0\ref\RestaurantAPI.DataAccess.dll" />
    <None Include="obj\Debug\net10.0\Restaura.39FB4F55.Up2Date" />
    <None Include="obj\Debug\net10.0\RestaurantAPI.DataAccess.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net10.0\RestaurantAPI.DataAccess.assets.cache" />
    <None Include="obj\Debug\net10.0\RestaurantAPI.DataAccess.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net10.0\RestaurantAPI.DataAccess.csproj.CoreCompileInputs.cache" />
    <None Include="obj\Debug\net10.0\RestaurantAPI.DataAccess.dll" />
    <None Include="obj\Debug\net10.0\RestaurantAPI.DataAccess.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\Debug\net10.0\RestaurantAPI.DataAccess.genruntimeconfig.cache" />
    <None Include="obj\Debug\net10.0\RestaurantAPI.DataAccess.pdb" />
    <None Include="obj\project.nuget.cache" />
    <None Include="obj\RestaurantAPI.DataAccess.csproj.nuget.g.props" />
    <None Include="obj\RestaurantAPI.DataAccess.csproj.nuget.g.targets" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
