<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="obj\Debug\net10.0\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs" />
    <Compile Include="obj\Debug\net10.0\RestaurantAPI.API.AssemblyInfo.cs" />
    <Compile Include="obj\Debug\net10.0\RestaurantAPI.API.GlobalUsings.g.cs" />
    <Compile Include="obj\Debug\net10.0\RestaurantAPI.API.MvcApplicationPartsAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net10.0\appsettings.Development.json" />
    <Content Include="bin\Debug\net10.0\appsettings.json" />
    <Content Include="bin\Debug\net10.0\RestaurantAPI.API.deps.json" />
    <Content Include="bin\Debug\net10.0\RestaurantAPI.API.runtimeconfig.json" />
    <Content Include="bin\Debug\net10.0\RestaurantAPI.API.staticwebassets.endpoints.json" />
    <Content Include="obj\Debug\net10.0\RestaurantAPI.API.csproj.FileListAbsolute.txt" />
    <Content Include="obj\Debug\net10.0\rjsmcshtml.dswa.cache.json" />
    <Content Include="obj\Debug\net10.0\rjsmrazor.dswa.cache.json" />
    <Content Include="obj\Debug\net10.0\rpswa.dswa.cache.json" />
    <Content Include="obj\Debug\net10.0\staticwebassets.build.endpoints.json" />
    <Content Include="obj\Debug\net10.0\staticwebassets.build.json" />
    <Content Include="obj\Debug\net10.0\staticwebassets.removed.txt" />
    <Content Include="obj\project.assets.json" />
    <Content Include="obj\RestaurantAPI.API.csproj.nuget.dgspec.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RestaurantAPI.Domain\RestaurantAPI.Domain.csproj" />
    <ProjectReference Include="..\RestaurantAPI.DataAccess\RestaurantAPI.DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Middlewares\" />
    <Folder Include="obj\Debug\net10.0\staticwebassets\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\net10.0\AutoMapper.dll" />
    <None Include="bin\Debug\net10.0\AutoMapper.Extensions.Microsoft.DependencyInjection.dll" />
    <None Include="bin\Debug\net10.0\Azure.Core.dll" />
    <None Include="bin\Debug\net10.0\Azure.Identity.dll" />
    <None Include="bin\Debug\net10.0\cs\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\cs\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\cs\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\cs\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\de\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\de\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\de\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\de\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\es\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\es\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\es\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\es\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\fr\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\fr\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\fr\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\fr\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\Humanizer.dll" />
    <None Include="bin\Debug\net10.0\it\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\it\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\it\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\it\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\ja\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\ja\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\ja\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\ja\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\ko\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\ko\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\ko\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\ko\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.AspNetCore.OpenApi.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.Bcl.AsyncInterfaces.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.CodeAnalysis.CSharp.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.CodeAnalysis.CSharp.Workspaces.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.CodeAnalysis.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.CodeAnalysis.Workspaces.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.Data.SqlClient.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.EntityFrameworkCore.Abstractions.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.EntityFrameworkCore.Design.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.EntityFrameworkCore.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.EntityFrameworkCore.Relational.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.EntityFrameworkCore.SqlServer.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.Extensions.DependencyModel.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.Identity.Client.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.Identity.Client.Extensions.Msal.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.IdentityModel.Abstractions.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.IdentityModel.JsonWebTokens.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.IdentityModel.Logging.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.IdentityModel.Protocols.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.IdentityModel.Protocols.OpenIdConnect.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.IdentityModel.Tokens.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.OpenApi.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.SqlServer.Server.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.Win32.SystemEvents.dll" />
    <None Include="bin\Debug\net10.0\Mono.TextTemplating.dll" />
    <None Include="bin\Debug\net10.0\pl\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\pl\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\pl\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\pl\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\pt-BR\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\pt-BR\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\pt-BR\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\pt-BR\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\RestaurantAPI.API.dll" />
    <None Include="bin\Debug\net10.0\RestaurantAPI.API.exe" />
    <None Include="bin\Debug\net10.0\RestaurantAPI.API.pdb" />
    <None Include="bin\Debug\net10.0\RestaurantAPI.DataAccess.dll" />
    <None Include="bin\Debug\net10.0\RestaurantAPI.DataAccess.pdb" />
    <None Include="bin\Debug\net10.0\RestaurantAPI.Domain.dll" />
    <None Include="bin\Debug\net10.0\RestaurantAPI.Domain.pdb" />
    <None Include="bin\Debug\net10.0\runtimes\unix\lib\net6.0\Microsoft.Data.SqlClient.dll" />
    <None Include="bin\Debug\net10.0\runtimes\unix\lib\net6.0\System.Drawing.Common.dll" />
    <None Include="bin\Debug\net10.0\runtimes\win-arm64\native\Microsoft.Data.SqlClient.SNI.dll" />
    <None Include="bin\Debug\net10.0\runtimes\win-arm\native\Microsoft.Data.SqlClient.SNI.dll" />
    <None Include="bin\Debug\net10.0\runtimes\win-x64\native\Microsoft.Data.SqlClient.SNI.dll" />
    <None Include="bin\Debug\net10.0\runtimes\win-x86\native\Microsoft.Data.SqlClient.SNI.dll" />
    <None Include="bin\Debug\net10.0\runtimes\win\lib\net6.0\Microsoft.Data.SqlClient.dll" />
    <None Include="bin\Debug\net10.0\runtimes\win\lib\net6.0\Microsoft.Win32.SystemEvents.dll" />
    <None Include="bin\Debug\net10.0\runtimes\win\lib\net6.0\System.Drawing.Common.dll" />
    <None Include="bin\Debug\net10.0\runtimes\win\lib\net6.0\System.Runtime.Caching.dll" />
    <None Include="bin\Debug\net10.0\runtimes\win\lib\net6.0\System.Security.Cryptography.ProtectedData.dll" />
    <None Include="bin\Debug\net10.0\runtimes\win\lib\net6.0\System.Windows.Extensions.dll" />
    <None Include="bin\Debug\net10.0\ru\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\ru\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\ru\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\ru\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\Swashbuckle.AspNetCore.Swagger.dll" />
    <None Include="bin\Debug\net10.0\Swashbuckle.AspNetCore.SwaggerGen.dll" />
    <None Include="bin\Debug\net10.0\Swashbuckle.AspNetCore.SwaggerUI.dll" />
    <None Include="bin\Debug\net10.0\System.ClientModel.dll" />
    <None Include="bin\Debug\net10.0\System.CodeDom.dll" />
    <None Include="bin\Debug\net10.0\System.Composition.AttributedModel.dll" />
    <None Include="bin\Debug\net10.0\System.Composition.Convention.dll" />
    <None Include="bin\Debug\net10.0\System.Composition.Hosting.dll" />
    <None Include="bin\Debug\net10.0\System.Composition.Runtime.dll" />
    <None Include="bin\Debug\net10.0\System.Composition.TypedParts.dll" />
    <None Include="bin\Debug\net10.0\System.Configuration.ConfigurationManager.dll" />
    <None Include="bin\Debug\net10.0\System.Drawing.Common.dll" />
    <None Include="bin\Debug\net10.0\System.IdentityModel.Tokens.Jwt.dll" />
    <None Include="bin\Debug\net10.0\System.Memory.Data.dll" />
    <None Include="bin\Debug\net10.0\System.Runtime.Caching.dll" />
    <None Include="bin\Debug\net10.0\System.Security.Cryptography.ProtectedData.dll" />
    <None Include="bin\Debug\net10.0\System.Security.Permissions.dll" />
    <None Include="bin\Debug\net10.0\System.Windows.Extensions.dll" />
    <None Include="bin\Debug\net10.0\tr\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\tr\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\tr\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\tr\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hans\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hans\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hans\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hans\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hant\Microsoft.CodeAnalysis.CSharp.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hant\Microsoft.CodeAnalysis.CSharp.Workspaces.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hant\Microsoft.CodeAnalysis.resources.dll" />
    <None Include="bin\Debug\net10.0\zh-Hant\Microsoft.CodeAnalysis.Workspaces.resources.dll" />
    <None Include="obj\Debug\net10.0\apphost.exe" />
    <None Include="obj\Debug\net10.0\refint\RestaurantAPI.API.dll" />
    <None Include="obj\Debug\net10.0\ref\RestaurantAPI.API.dll" />
    <None Include="obj\Debug\net10.0\Restaura.27F02E9B.Up2Date" />
    <None Include="obj\Debug\net10.0\RestaurantAPI.API.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net10.0\RestaurantAPI.API.assets.cache" />
    <None Include="obj\Debug\net10.0\RestaurantAPI.API.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net10.0\RestaurantAPI.API.csproj.CoreCompileInputs.cache" />
    <None Include="obj\Debug\net10.0\RestaurantAPI.API.dll" />
    <None Include="obj\Debug\net10.0\RestaurantAPI.API.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\Debug\net10.0\RestaurantAPI.API.genruntimeconfig.cache" />
    <None Include="obj\Debug\net10.0\RestaurantAPI.API.MvcApplicationPartsAssemblyInfo.cache" />
    <None Include="obj\Debug\net10.0\RestaurantAPI.API.pdb" />
    <None Include="obj\Debug\net10.0\staticwebassets.build.json.cache" />
    <None Include="obj\Debug\net10.0\swae.build.ex.cache" />
    <None Include="obj\project.nuget.cache" />
    <None Include="obj\RestaurantAPI.API.csproj.nuget.g.props" />
    <None Include="obj\RestaurantAPI.API.csproj.nuget.g.targets" />
  </ItemGroup>

</Project>
